name: sales_rep_visit_tracker_feature
description: "Your task is to build a Visits Tracker feature for a Route-to-Market (RTM) Sales Force Automation app. Design and structure your solution as though this feature is part of a larger, scalable application."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.8.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.6
  intl: ^0.18.1
  badges: ^3.1.2
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  fluttertoast: ^8.2.10
  fl_chart: ^0.71.0
  dots_indicator: ^4.0.1
  flutter_secure_storage: ^9.2.4
  logger: ^2.6.0
  flutter_native_splash: ^2.4.4
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  mocktail: ^1.0.0
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/ic_icon.png
  android: true
  android_12:
    image: assets/ic_icon.png
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_icon.png"
  min_sdk_android: 21
